version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=reclame_db
      - POSTGRES_USER=reclame_user
      - POSTGRES_PASSWORD=reclame_pass
    ports:
      - "5433:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=reclame_db
      - POSTGRES_USER=reclame_user
      - POSTGRES_PASSWORD=reclame_pass
      - POSTGRES_HOST=db

volumes:
  postgres_data:
