# Generated by Django 4.2.30 on 2026-09-09 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='fraud_alert',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='risk_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='complaint_evidences/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
