# Generated by Django 4.2.30 on 2026-09-09 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyprofile_fraud_alert_companyprofile_risk_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('OFFENSIVE', 'Linguagem Ofensiva / Inapropriada'), ('PERSONAL_DATA', 'Exposição de Dados Pessoais (LGPD)'), ('FALSE_FRAUD', 'Denúncia Falsa / Difamação'), ('OTHER', 'Outros Motivos')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente de Análise'), ('APPROVED', 'Aprovado (Conteúdo Moderado)'), ('REJECTED', 'Rejeitado (Improcedente)')], db_index=True, default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.complaint')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(db_index=True, max_length=50)),
                ('target_id', models.IntegerField(db_index=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
