# Generated by Django 4.2.30 on 2026-09-17 23:45

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Status de verificação e autenticidade da empresa'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verification_document',
            field=models.FileField(blank=True, help_text='Documento de comprovação da empresa (PDF/PNG/JPG)', null=True, upload_to=core.models.company_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
