# Generated by Django 4.2.30 on 2026-09-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='integrity_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='settlement_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Selo Digital Imutável de Acordo Resolutivo', max_length=64, null=True),
        ),
    ]
